# Elasticsearch Configuration
# Version: 8.9.0
# Purpose: Production configuration for knowledge aggregation system

#----------------------
# Cluster Settings
#----------------------
cluster.name: knowledge-aggregation-es
discovery.type: single-node
discovery.seed_hosts: ["localhost"]
cluster.initial_master_nodes: ["${HOSTNAME}"]

# Disk-based shard allocation
cluster.routing.allocation.disk.threshold_enabled: true
cluster.routing.allocation.disk.watermark.low: "85%"
cluster.routing.allocation.disk.watermark.high: "90%"

#----------------------
# Node Settings
#----------------------
node.name: "${HOSTNAME}"
node.master: true
node.data: true
node.ingest: true
node.attr.box_type: hot

#----------------------
# Path Settings
#----------------------
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs
path.repo: /usr/share/elasticsearch/snapshots

#----------------------
# Network Settings
#----------------------
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300

# CORS Settings
http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-methods: "OPTIONS, HEAD, GET, POST, PUT, DELETE"
http.cors.allow-headers: "X-Requested-With, Content-Type, Content-Length, Authorization"

#----------------------
# Memory Settings
#----------------------
bootstrap.memory_lock: true
indices.memory.index_buffer_size: "30%"
indices.queries.cache.size: "20%"
indices.fielddata.cache.size: "20%"

# Circuit Breaker Settings
indices.breaker.total.use_real_memory: true
indices.breaker.fielddata.limit: "40%"
indices.breaker.request.limit: "30%"

#----------------------
# Security Settings
#----------------------
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.keystore.path: elastic-certificates.p12

# Audit and Monitoring
xpack.security.audit.enabled: true
xpack.monitoring.collection.enabled: true
xpack.monitoring.collection.interval: 30s

#----------------------
# Performance Settings
#----------------------
# Thread Pool Configuration
thread_pool.write.queue_size: 1000
thread_pool.search.queue_size: 1000
thread_pool.get.queue_size: 1000

# Recovery Settings
indices.recovery.max_bytes_per_sec: "50mb"
indices.recovery.max_concurrent_file_chunks: 5

# Search Settings
search.max_buckets: 10000
search.default_search_timeout: "30s"

# Destructive Action Protection
action.destructive_requires_name: true