# Kubernetes API version: v1
# Purpose: Define sensitive configuration and credentials for knowledge system microservices
# Security: AES-256 encryption at rest, RBAC controls, and 30-day rotation policy
apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secrets
  namespace: knowledge-system
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: knowledge-aggregation
  annotations:
    encryption.kubernetes.io/key: k8s:enc:aes256:v1
    secret.kubernetes.io/rotation-interval: "30d"
    secret.kubernetes.io/auto-rotation: "true"
type: Opaque
data:
  jwt-signing-key: ${JWT_SIGNING_KEY}
  auth-public-key: ${AUTH_PUBLIC_KEY}
  auth-private-key: ${AUTH_PRIVATE_KEY}
---
apiVersion: v1
kind: Secret
metadata:
  name: content-discovery-secrets
  namespace: knowledge-system
  labels:
    app.kubernetes.io/name: content-discovery
    app.kubernetes.io/part-of: knowledge-aggregation
  annotations:
    encryption.kubernetes.io/key: k8s:enc:aes256:v1
    secret.kubernetes.io/rotation-interval: "30d"
    secret.kubernetes.io/auto-rotation: "true"
type: Opaque
data:
  youtube-api-key: ${YOUTUBE_API_KEY}
  spotify-client-id: ${SPOTIFY_CLIENT_ID}
  spotify-client-secret: ${SPOTIFY_CLIENT_SECRET}
  google-books-api-key: ${GOOGLE_BOOKS_API_KEY}
---
apiVersion: v1
kind: Secret
metadata:
  name: vector-service-secrets
  namespace: knowledge-system
  labels:
    app.kubernetes.io/name: vector-service
    app.kubernetes.io/part-of: knowledge-aggregation
  annotations:
    encryption.kubernetes.io/key: k8s:enc:aes256:v1
    secret.kubernetes.io/rotation-interval: "30d"
    secret.kubernetes.io/auto-rotation: "true"
type: Opaque
data:
  pinecone-api-key: ${PINECONE_API_KEY}
  pinecone-environment: ${PINECONE_ENVIRONMENT}
  redis-password: ${REDIS_PASSWORD}
  redis-tls-cert: ${REDIS_TLS_CERT}
---
apiVersion: v1
kind: Secret
metadata:
  name: knowledge-organization-secrets
  namespace: knowledge-system
  labels:
    app.kubernetes.io/name: knowledge-organization
    app.kubernetes.io/part-of: knowledge-aggregation
  annotations:
    encryption.kubernetes.io/key: k8s:enc:aes256:v1
    secret.kubernetes.io/rotation-interval: "30d"
    secret.kubernetes.io/auto-rotation: "true"
type: Opaque
data:
  neo4j-username: ${NEO4J_USERNAME}
  neo4j-password: ${NEO4J_PASSWORD}
  neo4j-connection-url: ${NEO4J_CONNECTION_URL}
  graph-encryption-key: ${GRAPH_ENCRYPTION_KEY}
---
apiVersion: v1
kind: Secret
metadata:
  name: output-generation-secrets
  namespace: knowledge-system
  labels:
    app.kubernetes.io/name: output-generation
    app.kubernetes.io/part-of: knowledge-aggregation
  annotations:
    encryption.kubernetes.io/key: k8s:enc:aes256:v1
    secret.kubernetes.io/rotation-interval: "30d"
    secret.kubernetes.io/auto-rotation: "true"
type: Opaque
data:
  notion-integration-token: ${NOTION_INTEGRATION_TOKEN}
  notion-workspace-id: ${NOTION_WORKSPACE_ID}
  export-signing-key: ${EXPORT_SIGNING_KEY}