version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.45.0  # Latest stable version
    ports:
      # UDP port for accepting jaeger.thrift in compact Thrift protocol used by most current Jaeger clients
      - "6831:6831/udp"
      # HTTP port for accepting spans in Jaeger Thrift format
      - "14250:14250"
      # HTTP port for serving Web UI and API
      - "16686:16686"
      # Port for accepting Zipkin spans
      - "9411:9411"
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
      - ES_USERNAME=${ES_USERNAME:-elastic}
      - ES_PASSWORD=${ES_PASSWORD:-changeme}
      - ES_NUM_REPLICAS=1
      - ES_NUM_SHARDS=5
      - ES_INDEX_PREFIX=jaeger
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - MEMORY_MAX_TRACES=50000
      - QUERY_BASE_PATH=/jaeger
      - LOG_LEVEL=info
      # Memory limits aligned with production k8s specs
      - MEMORY_STORAGE_MAX_TRACES=50000
      - COLLECTOR_QUEUE_SIZE=2000
      - QUERY_STATIC_FILES=/usr/share/jaeger-ui-build/build
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:16686"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - tracing-network
    volumes:
      - jaeger-data:/badger
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G

volumes:
  jaeger-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/jaeger
      o: bind

networks:
  tracing-network:
    driver: bridge
    internal: false
    attachable: true
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
    labels:
      com.knowledge.aggregation.network.type: "tracing"
      com.knowledge.aggregation.network.environment: "development"