# Prometheus Configuration v2.45.0
# Global configuration for the Prometheus server
global:
  # How frequently to scrape targets
  scrape_interval: 15s
  # How frequently to evaluate rules
  evaluation_interval: 15s
  # Per-scrape timeout
  scrape_timeout: 10s
  # External labels for federation and remote storage
  external_labels:
    environment: production
    cluster: knowledge-platform

# Rule files to load
rule_files:
  - /etc/prometheus/rules/system.rules.yml
  - /etc/prometheus/rules/api.rules.yml
  - /etc/prometheus/rules/vector.rules.yml
  - /etc/prometheus/rules/content.rules.yml

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
      # Alertmanager timeout and other settings
      timeout: 10s
      scheme: http
      path_prefix: /

# Scrape configurations
scrape_configs:
  # API Gateway monitoring
  - job_name: api-gateway
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets:
          - api-gateway:8080
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: (.*)
        replacement: $1
      - source_labels: [__address__]
        target_label: service
        regex: (.*)
        replacement: api-gateway

  # Content Discovery Service monitoring
  - job_name: content-discovery
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets:
          - content-discovery:8000
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: (.*)
        replacement: $1
      - source_labels: [__address__]
        target_label: service
        regex: (.*)
        replacement: content-discovery

  # Vector Service monitoring
  - job_name: vector-service
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets:
          - vector-service:8001
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: (.*)
        replacement: $1
      - source_labels: [__address__]
        target_label: service
        regex: (.*)
        replacement: vector-service

  # Node Exporter for hardware and OS metrics
  - job_name: node-exporter
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets:
          - node-exporter:9100
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: (.*)
        replacement: $1
      - source_labels: [__address__]
        target_label: service
        regex: (.*)
        replacement: node-exporter

# Storage configuration
storage:
  tsdb:
    # Retention settings
    retention.time: 15d
    # Maximum block duration
    retention.size: 0
    # Enable WAL compression
    wal_compression: true
    # Out of order time window
    out_of_order_time_window: 10m

# Remote write configuration (optional, commented out)
# remote_write:
#   - url: "http://remote-storage:9201/write"
#     remote_timeout: 30s
#     queue_config:
#       capacity: 10000
#       max_shards: 200
#       max_samples_per_send: 500

# Remote read configuration (optional, commented out)
# remote_read:
#   - url: "http://remote-storage:9201/read"
#     read_recent: true
#     remote_timeout: 30s

# Query configuration
query:
  # Maximum number of concurrent queries
  max_concurrency: 20
  # Timeout for queries
  timeout: 2m
  # Maximum samples in a query
  max_samples: 50000000