# Grafana version: 9.5.3
# Datasources configuration for metrics, tracing and logging visualization
# External dependencies:
# - prometheus v2.45.0: Time series database for metrics
# - jaeger v1.47.0: Distributed tracing system
# - elasticsearch v8.9.0: Log aggregation and search

apiVersion: 1

datasources:
  # Prometheus datasource configuration for system and business metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: false
    jsonData:
      # Optimized query performance settings
      timeInterval: "15s"
      queryTimeout: "30s"
      httpMethod: POST
      keepCookies: []
      scrapeInterval: "15s"
      # Link exemplars to Jaeger traces
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: jaeger

  # Jaeger datasource configuration for distributed tracing
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger-query:16686
    version: 1
    editable: false
    jsonData:
      # Enable node graph visualization
      nodeGraph:
        enabled: true
      # Configure trace to log correlation
      tracesToLogs:
        datasourceUid: elasticsearch
        tags: 
          - service
          - error
        mappedTags:
          - key: service.name
            value: service
          - key: error
            value: error

  # Elasticsearch datasource configuration for log aggregation
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: logstash-*
    version: 1
    editable: false
    jsonData:
      # Elasticsearch-specific settings
      timeField: "@timestamp"
      esVersion: "8.9.0"
      maxConcurrentShardRequests: 5
      logMessageField: message
      logLevelField: level
      interval: Daily
      timeInterval: "10s"
      fieldsSeparator: "."
      includeFrozen: false